#!/bin/bash 

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo apt install python-pip
sudo -H pip install websocket-server

# Copy the app
SERVICE_NAME=camel-race-server
echo "Make sure that we start the app on startup"
sudo cp $DIR/$SERVICE_NAME.service /etc/systemd/system/
sudo bash -c "echo 'ExecStart=/usr/bin/python -u $DIR/server.py --ip 192.168.0.1 --port 3000' >> /etc/systemd/system/$SERVICE_NAME.service"
sudo systemctl enable $SERVICE_NAME.service

